### ISSUE TITLE
Incorrect display - buttons don't fit in the window vertically

### ISSUE THREAD

**Issue by GrimPixel** [rybak/resoday#4]
I tried to scroll my mouse wheel. Nothing happened.
![b](https://github.com/rybak/resoday/assets/39795763/6309398d-8e80-4593-8b2f-fe1222e7778e)

System.currentTimeMillis	1694699690225
ZonedDateTime.now (UTC)	2023-09-14T13:54:50.227587996Z[UTC]
os.arch	amd64
os.name	Linux
os.version	6.1.49-1-MANJARO
java.version	20.0.2
java.vendor	N/A
java.vendor.url	https://openjdk.org/
file.encoding	UTF-8
Runtime.availableProcessors	4
Runtime.maxMemory	3103784960
Runtime.totalMemory	199229440
Runtime.version	20.0.2+9
Resoday.title	Resoday built by Andrei Rybak
Resoday.version	1.7
Resoday.formatVersion	2

**Comment by rybak** [comment]
Hello, @GrimPixel. Thank you for your interest in Resoday.

This is a known issue - support for smaller displays is lacking. Could you please share, what is the resolution of the monitor you are using for Resoday? If it is big enough, you should be able to simply stretch the window vertically.

TODO
- [x] add screen resolution to the debug info generated by `DebugDialog`

**Comment by GrimPixel** [comment]
Hi. My screen is 1080p and I am using the 1280x720 resolution.

**Comment by rybak** [comment]
The issue should be fixed in the [latest release](https://github.com/rybak/resoday/releases). I'd love to know if it's working better for you now. Could you please give it a try and let me know if everything seems okay on your end?

![Screenshot_20230916 Resoday scrollbars](https://github.com/rybak/resoday/assets/624072/7e5ca53c-ee97-4d91-af67-886eee0c6617 "Resoday now uses scrollbars, if there isn't enough room for all calendar buttons in the window")

**Comment by GrimPixel** [comment]
Yes, it displayed well and the mouse wheel worked.
